server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
  - job_name: "test-log"
    static_configs:
      - targets:
          - localhost
        labels:
          job: "test-logs"
          __path__: /home/lourobert/acaton/test.log
